"""add encounters, refactor content dropsource

Revision ID: 50a67e541212
Revises: b005182f85d9
Create Date: 2026-05-15 04:37:05.999637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '50a67e541212'
down_revision: Union[str, None] = 'b005182f85d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encounters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raidbots_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('patch_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['patch_version'], ['patch_versions.version'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raidbots_id')
    )
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raidbots_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.alter_column('name_kr',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_unique_constraint('uq_contents_raidbots_id', ['raidbots_id'])
        batch_op.drop_column('difficulty')

    with op.batch_alter_table('drop_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encounter_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('uq_dropsource_item_encounter', ['item_id', 'encounter_id'])
        # drop_constraint(None) 제거: SQLite anonymous FK 이름 충돌 위험.
        # drop_column('content_id')가 content_id→contents FK를 batch 재생성 시 자동 제거함.
        batch_op.create_foreign_key('fk_dropsource_encounter', 'encounters', ['encounter_id'], ['id'])
        batch_op.drop_column('content_id')
        batch_op.drop_column('boss_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drop_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('boss_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('content_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_dropsource_encounter', type_='foreignkey')
        batch_op.create_foreign_key('fk_dropsource_content', 'contents', ['content_id'], ['id'])
        batch_op.drop_constraint('uq_dropsource_item_encounter', type_='unique')
        batch_op.drop_column('encounter_id')

    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint('uq_contents_raidbots_id', type_='unique')
        batch_op.alter_column('name_kr',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('name_en')
        batch_op.drop_column('raidbots_id')

    op.drop_table('encounters')
    # ### end Alembic commands ###
