"""add spec_slot_item_popularity table

Revision ID: b005182f85d9
Revises: 01cd55c4ba38
Create Date: 2026-05-14 03:16:04.906470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b005182f85d9'
down_revision: Union[str, None] = '01cd55c4ba38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spec_slot_item_popularity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('spec_name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('slot', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('total_sample', sa.Integer(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_name', 'spec_name', 'content_type', 'slot', 'item_id', name='uq_ssip_item')
    )
    op.create_index('ix_ssip_lookup', 'spec_slot_item_popularity', ['class_name', 'spec_name', 'content_type', 'slot'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ssip_lookup', table_name='spec_slot_item_popularity')
    op.drop_table('spec_slot_item_popularity')
    # ### end Alembic commands ###
